apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mysql-pvc
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data "
  storageClassName: record

